version: '3'
services:
  mysql:
    build: ./mysql
    container_name: douban_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=douban
    command: mysqld --default-authentication-plugin=mysql_native_password
  adminer:
    image: adminer:4
    container_name: douban_adminer
    ports:
      - 8080:8080
    links:
      - mysql
  scrapyd:
    build: ./scrapyd
    container_name: douban_scrapyd
    ports:
      - 6800:6800
    environment:
      - TZ=Asia/Chongqing
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=public
      - MYSQL_DB=douban
    links:
      - mysql
